### ISSUE TITLE
Data Visualizations for Yearn - 2nd Month

### ISSUE THREAD

**Issue by kyhoon** [yearn/budget#100]
### Scope

![image](https://user-images.githubusercontent.com/30872891/196290798-dd9399d7-2eec-4a47-b732-b4ca09112cad.png)

![image](https://user-images.githubusercontent.com/30872891/196290827-62f76ef9-0f2c-4172-afcc-c00a3882574a.png)

The current state of the app can be seen at https://ydata.vercel.app

This is a follow-up request from [the previous request for the data visualization project](https://github.com/yearn/budget/issues/89), the details of which could be seen in the comment section of the issue. Before we ask for an extension, we would like to first share the current progress of the project.

### yData

![image](https://user-images.githubusercontent.com/30872891/196290917-2824209b-4454-44ba-8878-1efd80c438c1.png)

[yData](https://github.com/yearn/ydata) is the new branding of the previous yearn-data-analytics repo. We aim to use this web app and the repository to share the results from our research, and potentially also use this space to serve products that are directly related to the research results.

As mentioned above, the app is currently deployed using vercel: https://ydata.vercel.app

yData currently holds two visualizations:
* [Yearn V2 Vaults](https://ydata.vercel.app/visualizations/yearn-v2-vaults)
* [Efficient Frontier](https://ydata.vercel.app/visualizations/efficient-frontier)

The Yearn V2 Vaults is an interactive dashboard that illustrates the various statistics of our vault assets. Efficient Frontier is a simple datapane report that lets the users compare the performance of Yearn's assets against the whole DeFi space.

### Social Media

Although this was not within our action items, we found out that our [YFI Interns Twitter account](https://twitter.com/YFI_interns) was dormant since the last RT on the 9th of June.
Thus we decided to reactivate this account to start delivering the data-driven narratives. 

![image](https://user-images.githubusercontent.com/30872891/196291080-0a0e2544-db5b-4ef1-97a8-2172d817dce3.png)

We tried out some [simple tweets about our vaults](https://twitter.com/YFI_interns/status/1574752793738485763?s=20&t=8-XYhoTBstBIYPT1XRWk8g) to measure the level of traction the account was able to reach. We will continue to post these simple weekly data reports and also continue the RTs for the main account to gradually regain the audience back to the Interns account.

We also created a Discord channel dedicated to the data visualization projects (thanks to Dark) named \#data-science in Yearn Talk. We will be cross-posting the tweets and sharing the updates for the yData app in this channel.

### Shortfalls

The items that we promised for the first month were the following:

1. Create a frontend server to embed the visualizations using our web template
2. Create a visualization of the efficient frontier of DeFi assets

Thus it may seem like we did deliver the above two items on the surface. However, there are a few shortfalls for both items that we did not manage to fulfill.

For 1, we did set up the template but still need to work on the overall branding and creating a better UX. Marco Worms recently joined the team to help us out on this issue.

For 2, the current efficient frontier is built upon only the stablecoins data instead of the whole set of DeFi assets. Also, the current visualization is missing the backtest results of the exemplary portfolios.
The main blocking factor for this was that we had to fetch the price of an arbitrary token on a specific chain, at a given block. We are planning on combining the new coin API from [DefiLlama](https://defillama.com/docs/api) and the [ypricemagic](https://github.com/BobTheBuidler/ypricemagic) to tackle this issue.

For both 1 and 2, we came across several mismatches in the data between the different data sources of Yearn during the project (e.g. https://github.com/yearn/yearn-exporter/issues/393). Thus we had to spend some time checking the integrity of the data and rebuilding the pipelines to fetch them from the correct source. We believe that this could be easily fixed after the upcoming update on [yDaemon](https://github.com/yearn/ydaemon).

### Plan

We would like to follow the original 3-month plan that we shared in [the first request](https://github.com/yearn/budget/issues/89), but with a couple of modifications.

**Second Month (Requested Month)**
* ~~Migrate the visualizations created by jameskbh to the frontend~~
* Create a visualization of our customers
    * Sample plot at https://chart-studio.plotly.com/~borrito/3/#/
    * Aims to help answer the following questions:
        * What other protocols do our clients use?
        * Were the recent withdrawals transitory?
        * How does the distribution of TVL for a single vault look like?
* (NEW) Update the visualizations
    * Update the structure of Yearn V2 Vaults
        * Sample draft at https://docs.google.com/document/d/11-WwulyYS1N91Z4wTAeCk2UPlS7oNixdUf_9GQInC1w/edit?usp=sharing
    * Update the data source and the backtest results for the efficient frontier
    * Provide documentation for the visualizations
        * Sample draft at https://docs.google.com/document/d/1w0jYpGDqViCOwn4MkiySBPGGEJX6h16rBXUDRKOMQUA/edit
* (NEW) Create a visualization of the tail-dependency of tokens
    * Sharing the recent research results of cs data, working within the strategist team
    * Create a graph visualization from the correlation of the token price volatilities
    * Aims to help answer the following questions:
        * Which tokens does a given token share its tail risk?
        * Which strategies should belong to the same risk group?
        * How should we diversify our TVL allocations?

The migration of the visualizations created by jameskbh has already begun in the first month. The Yearn V2 Vault visualization directly contains the contents from the [yVaults v2 Historical Overview](https://medium.com/@jameskbh/yvaults-v2-historical-overview-23a9a7db28a5), and also implicitly contains the narratives from [Yearn Vaults’ Stablecoins report: DAI, USDC, and USDT](https://medium.com/@jameskbh/yearn-vaults-stablecoins-report-dai-usdc-and-usdt-620dfc11c72f). Thus we now remove this item from the Second Month and instead replace it with the update item.

This data visualization project has been able to facilitate the exchange of ideas within the YFI Data Analysis group, and the tail-dependency graph is a short-term project that came to life from such ideations. cs data has been working on building forecast models for the price volatilities of different tokens. Although it may take some time until he can complete the model, it seemed beneficial to first take the contemporaneous part of the analysis and visualize it to share the results with the other teams of Yearn. We are planning to visualize this structure as a graph to give us a bird's-eye view of the risk landscape of different tokens.

### Deadline

2022-11-30

### People

List of team members and the responsibilities:

* borrito
    * implement the customer visualization
    * implement the tail-dependency of tokens
    * will be addressing all issues full-time
* huggingbot
    * maintain the frontend server
    * implement and maintain data pipelines (yearn-exporter, ydaemon)
* kofee
    * implement and maintain data pipelines (subgraph, yearn-exporter, ydaemon)
* jameskbh
    * keep creating visualizations in flourish studio
    * research other data visualization platforms
    * write articles and documentations for the data group
* marco worms (*not receiving remuneration from this grant*)
    * lead the branding of yData and its products
    * implement and enhance the frontend UI/UX
* cs data (*not receiving remuneration from this grant*)
    * give technical advice on the data scientific methods
    * implement the tail-dependency of tokens
* farrah (*not receiving remuneration from this grant*)
    * build out visualizations as needed
    * complete data analysis to arrive at answers to key business questions
    * define and build out POCs for net-new data products from visualizations developed by the team 
    * in charge of internal assessment of the performance and effectiveness of the project

The members will continue to support the other initiatives mentioned in [the previous budget request for the data team](https://github.com/yearn/budget/issues/87) as well.

### Money

$15,000 for a single month. After a month another request will be presented to support the next milestones of the project.

The budget will be streamed to the members noted above.

### Amount

15000 DAI, or YFI of equivalent value

### Wallet address

streamed to the contributors

### Reporting

- [X] I agree to post weekly updates

**Comment by saltyfacu** [comment]
Sorry for the delay! 

I’ve read both of your proposals with the whole 3 months plan. 

To clarify who will be using this, I have a question: which team/s are you working with to get the requirements and specs for the data and visualizations needed?

**Comment by kyhoon** [comment]
Thank you for the feedback!

This question indeed is very important and multi-faceted; We had to have a quick discussion on our main points. We will try to give the answer to your question in two steps, firstly by stating just simple facts on the collaboration, and secondly by answering directly on how we are doing the "requirements gathering" or the "user studies", which perhaps is closer to what you wanted to know.


### Short Version

We are currently communicating with the following teams:
1. Teams that are building the yDaemon, Yearn Exporter, and Yearn Subgraphs
2. Teams that are working for the B2B dashboard (fully overlaps with the previous item)
3. Vault Management Team
4. Creative/Social Team

More specifically, we are trying to implement data pipelines by communicating with 1 and 2, and we are trying to acquire and clarify the requirements and specs from 3 and 4.


### Longer Version

From how we understood the question, the gist here is to find out where the demand lies. Our intended use is for three different stakeholders:
* General Public: create overviews and metrics for yVaults (AUM, APY, Strategies) to highlight Yearn performance, generate traction, and showcase the information.
* Yearn Partners: provide visualizations for the B2B dashboard
* Other yTeams: assist their work by sharing the processed data, or by contributing to the data pipelines

when going into the specifics, each subtopic for the visualizations has a specific focus on one of the stakeholders:
1. Yearn V2 Vaults -> showcase the performance to the General Public 
2. B2B Dashboard -> showcase the performance to the Yearn Partners
3. Efficient Frontier -> assist the decision making of the Vault Management Team
4. Customer Visualization -> assist the market identification for the Creative/Social Team
5. Sentiment Analysis -> same as above
6. Volatility Forecasting -> assist the strategy development for the Strategists Team

3 and 6 are currently under discussion, 4 and 5 are yet to be arranged.

And for 1 and 2, although we have begun working on them, the current traction is quite low. We believe this is due to the lack of engagements we made in the previous month.

At the moment we have a rough sketch for a 3-phase design thinking framework to guide requirements gathering: Immersion, Ideation, and Implementation. During the immersion phase we engage with and observe our respective target audiences listed above. Based on what we learn, we define clear problem statements, come up with as many ideas and potential solutions and begin building prototypes and testing them. 
Some of the aspects of this process could go out of scope for the data visualization project and may be another important project on its own. This process will be led by Farrah, but all team members will take part in the market research and user interviews across internal and external stakeholders.

We hope that this addresses your questions and please feel free to leave additional questions and feedbacks.

**Comment by newmickymousse** [comment]
After analyzing your proposal thoroughly, we regret to inform you that we cannot approve it. We appreciate your effort to contribute to Yearn, but given the current market conditions, we are only approving expenses that contribute to Yearn's core teams or Yearn goals. We encourage you to present a new proposal in the future, and before doing so, we recommend that you work with current teams to draft more detailed specs that can help existing teams achieve their goals.

**Comment by kyhoon** [comment]
Thank you for the feedback! Will proceed to communicate with the other teams to come up with more detailed specs for the next proposal.
