### ISSUE TITLE
Maintain Written Content and Scale Yearn Knowledge Base

### ISSUE THREAD

**Issue by MarcoWorms** [yearn/budget#112]
### Scope

This is a request to extend #103, with some changes on scope and grant amount requested.

The scope of the proposal is:

- Maintain Yearn DevDocs
- Maintain Yearn Blog (Articles on Medium)
- UI Help: Vault Reports Generator Maintance + execute generating process every month 
- Ship and maintain yGenius (scale yearn knowledge base)

### Plan

The plan, as I've been doing for an year now and reported weekly in #69, #90, and #103, is to keep adding content to the docs and crafting new articles to onboard new users and highlight the main benefits of using Yearn, and also maintain documentation up-to-date for current and new products (ycrv, ybal, v3 vaults, vault factory).

I am always open to reasses the direction of what our content efforts should be aiming for!

And now I also want to add a new scope here: scale yearn knowledge base, which I intent to start with yGenius:

**yGenius and LLMs**

LLMs are here and I've been using them a lot to help making content. I believe that there is value in maintaining a sort of yearn index, currently using [gpt_index](https://github.com/jerryjliu/gpt_index), for the yearn eco so LLMs can know more about all the docs, code, articles, onchain/offchain data, support history, and beyond. Today yearn ecosystem has a lot of spread knowledge, hopefully this initiative helps anyone consume it more conveniently.

We released a first version + source here:
- https://medium.com/@marcoworms/ygenius-chat-with-yearn-efa17d3f0ec8

Automating process around updating the index, figuring out the sources to include, and properly indexing/labeling them is the effort I want to iterate on the next months. Here is a snapshot of today's index state, which has much space to improve just by properly adding existing data on it.

Here is an image with the current health of the index, and I'm exploring [ways](https://twitter.com/MarcoWorms/status/1625937940412043282) to fix the yellow circles (which means data is in index but bot is having difficulty to reach it)

![](https://i.imgur.com/w9NLe9l.png)

*In a sepparate effort I started [DocuDroid](https://twitter.com/DocuDroid) which is not much yearn related but I do use it to review written content I make for yearn.

### Deadline

2023-05-28

### People

Marco Worms: technical writer, web2 dev, ygenius project manager

### Money

A grant for me to continue writing articles, adding new content to the docs site, and maintaining yearn's LLM index. I will be able to fulltime these and won't need to do external freelances anymore with the new amount requested, which will help me focus.

Other Costs: OpenAI API costs, will paste one-week data here when we have it, but for projection it cost 10U$/day to allow people to make 1000 daily requests (always paid on-demand per-request) (I can pay this by myself and ask refund on end of month)

### Amount

Monthly: $7500 DAI + $2500 YFI (YFI can be veYFI locked for max duration)

### Wallet address

0xB1d693B77232D88a3C9467eD5619FfE79E80BCCc

### Reporting

Weekly

**Comment by fakenickels** [comment]
+1 well deserved!

**Comment by MarcoWorms** [comment]
- docs updates:
  - https://github.com/yearn/yearn-devdocs/pull/310
  - https://github.com/yearn/yearn-devdocs/pull/311
  - https://github.com/BobTheBuidler/ez-a-sync/pull/26
- drafting up yeth docs and syncing with draper for release materials (links in yeth docs group)
- finished draft for permissionless vault medium article, awaiting review: https://hackmd.io/Wf3aJlPAReerUFWwjyxn2w?view
-  yGenius: working on improving it from many angles, don't have a tangible progress yet but:  
   - strengthening partnership with makerdao by providing help for them to run their instance (mkrGenius), they intent to contribute back to our source so it's good to help evolve the product overall
   - experimenting with different llamaindex types and compositions so things like "onchain data" can be put together with "articles" within the same index, have learned some cool tricks but need to test more
   - IMO one of the best use-cases for current state of product is using for support so the team can try to use it and generate answers faster since they can validate what is or isn't a good answers and fix it. Didn't set this up formally with the ySupport team yet tho. 
- trying to make a forkable contract where people can donate yield for a cause https://github.com/MarcoWorms/yDonate
   - would like to write more docs on how to integrate with vaults on the code side, now that I've learned it better on the code side I want to produce more technical content around yearn smart contracts

**Comment by MarcoWorms** [comment]
- docs updates:
  - https://github.com/yearn/yearn-security/pull/73
- published factory vaults article, awaiting for tweet + medium publication from yearn
  - https://medium.com/p/dd4880116022
- Improved yDonate to use registry and accept any token, but now it has a bug I need to fix where if a new vault releases for a token then funds are stuck
  - https://github.com/MarcoWorms/yDonate
- working with bob on frontend for ypriceAPI, currently already working! temp link https://signature-colector.vercel.app/
  - approve DAI spending
  - subscribe ypriceAPI plan
  - sign message to use signature as API key for requests
  - <img width="1141" alt="Screenshot 2023-03-17 at 5 24 17 PM" src="https://user-images.githubusercontent.com/7863230/226072957-43ccfd18-da67-47fd-99c4-3c21e74e871b.png">

**Comment by MarcoWorms** [comment]
I have some stuff to do in the weekend that I should've done this week but will just lay down here all the current things:

- staying in sync with yeth group too do any needed texts for launch, there are some things to write like yip and comms
- jamming with bob on ypriceapi frontend ypriceapi.vercel.app (it is working to sub and generate signature that acts as API key, want to add some test request on the UI too)
- talking to major he said he would like an overhaul on weblib and ydaemon docs, the main pain point being that keeping docs up-to-date with code is a pain, today we are not using docs generated by docstrings so I will start an effort to create docs generated from the code/comments so dev doesn't have to update any text external to code files after doing a change
- exploring robowoofy to replicate it and make an article about how to run it in your own multisig/telegram
- working on a twitter thread that has similar content to 'yearn finance explained" which is the article with most engagement I made in yearn, gonna coordinating draper for cooler copy

**Comment by MarcoWorms** [comment]
- ypriceapi frontend is fully functional and now writing an article/tutorial for its release, syncing with bob and trying to help ship this project. Since it can be a potential revenue source I am focusing more on it rn as "finding new revenue sources" is a direction I'd like to explore with this grant.
  - https://ypriceapi-beta.yearn.finance/
  - not logged in: <img width="897" alt="Screenshot 2023-03-31 at 10 03 05 PM" src="https://user-images.githubusercontent.com/7863230/229266611-7348a976-4dc9-40c4-9229-54838c5cb771.png">
  - logged in: <img width="897" alt="Screenshot 2023-03-31 at 10 04 16 PM" src="https://user-images.githubusercontent.com/7863230/229266652-3412db70-3e1a-490c-9488-35abc9220c9c.png">
  - signed message, which is used as API key fore requests in ypriceAPI: <img width="1320" alt="Screenshot 2023-03-31 at 10 04 46 PM" src="https://user-images.githubusercontent.com/7863230/229266666-7cf8604b-4b15-49d0-9f58-2dad2a8581bc.png">
  - approved DAI spending to subscribe for a plan: <img width="1030" alt="Screenshot 2023-03-31 at 10 05 29 PM" src="https://user-images.githubusercontent.com/7863230/229266696-4d284fd0-bba1-42ae-a198-aa64e6934503.png">
  - TODO: add countdown after sub is done showing which pan is subscribed and how much time is left (should be done this WE!)
  - the tutorial/article is being done here: https://hackmd.io/tYsgIt4kQ82S-wjyGZyiYg

- ygenius
  - updated model from davinci-3 to 3.5-turbo, which is faster and cheaper
  - try it out! https://ygenius.yearn.farm/
  - waiting for access to chatGPT plugin API instead our current indexing method, I want to make a yearn plugin and explore what can be done from there, seems a good infrastructure to do this

- just registering here for the sake of logging, made this thread trying to go over some very basic stuff for people that don't know what is yearn and link to more complex places: https://twitter.com/MarcoWorms/status/1640580650574168064

**Comment by MarcoWorms** [comment]
gngn! I am coming back from my ethdenver/US staying and should start pushing things faster! atm this week I worked on:

- ypriceAPI: bob, ghosty, and I are stressing and fixing the v0 so we can release this product, the prints are similar to last week the visuals didn't change much, also working on a tutorial https://hackmd.io/tYsgIt4kQ82S-wjyGZyiYg but will first finish the FE
- made a quick call with korin about yeth to align how I can best help him in the process of boostrap/release in the docs side, mainly to get his perspective on what he thinks is important to be explicited in them about our tech
- talked with schlag about making a documentation for v3, we already have one queued https://github.com/yearn/yearn-devdocs/pull/291 but this one is mostly a tech specs/docs. I want to make a docs that will show at the code level, with example contracts:
  - how to integrate v3 as a partner 
  - how to create strategies/vaults compatible with v3/yearn
  - anything else that might need code examples so people can easily integrate or build from it

**Comment by MarcoWorms** [comment]
- [ypriceAPI](https://github.com/MarcoWorms/ypriceapi)
  - syncing with bob to finish docs + tutorial for this service, frontend got some alterations this week and seems ready at least for the test phase. 

- [devdocs](https://github.com/yearn/yearn-devdocs)
  - working on the following tutorials, no draft to show atm but am syncing with schlag to help me on the technical side, I want to have some "yearn.dev" (like react.dev) where devs can have great resources for building with v3, these are the topics outlined I think each 
    - how to integrate v3 vaults in partner website, redirecting funds to get the partner fees
    - how to write a v3-compatible strategy for a endorsed token
    - how to create an entire vault + strat for a non-endorsed token
  - working on some alterations on devdocs:
    - https://github.com/yearn/yearn-devdocs/pull/325
    - https://github.com/yearn/yearn-devdocs/issues/323

- [ygenius](https://ygenius.yearn.farm/)
  - the group is on fire in terms of ping-ponging around new ways to solve "indexing" and to make smarter agents for a specific eco. atm the greatest issue to us seems to be finding a way where the costs of smarter LLM queries justify the usage. IE we could make ygenius way smarter using gpt4 API, but each request would spike from 0.005 cents upwards to 0.25 cents (literally a 50x in price per request). so atm we are figuring out the best cost/bennefit/usability approaches and a niche to explore with these.
  - I recommend anyone at yearn interested in this joining the group, feel free to DM me and I link it to you
  - Workin with a contributor at the data analysis team at makerdao (tadeo), they have mkrGenius that is a fork from yGenius and we work on the bot plumbing processes together because there is a lot of problems that only needs solving once (how to best put large amounts of onchain data in the bot so I can answer questions about it?)

- [robowoofy](https://github.com/yearn/yearn-multisig-actions)
  - talking with dark ghosty I think we could spread robowoofy as article/twitter thread showing others how to run it. did not start this yet but intent to pushi this forward
  - there is an intersection that I want to explore with https://github.com/MarcoWorms/repo-radar where we can maybe add a feature in robowoofy for it to summarize the multiseg transaction by looking at the trx opcode and summarizing what is happening for that trx along with the link on the telegram message

- [dank-mids](https://github.com/BobTheBuidler/dank_mids)
  - exploring with bob possibilities of optimizing by rewriting it entirely in GO or rust, we are also experimenting using gpt4 32k context API for this (even though I don't have proper access to it yet we are working around by lending from others hahaha)

- generated some images for yfu team using [ControlNet](https://www.reddit.com/r/StableDiffusion/comments/119o71b/a1111_controlnet_extension_explained_like_youre_5/), was nothing time-consuming and actually was very fun to do!
- smol twitter thread based on out tone-of-voice document trying to abstract away some learning that I think can be applied to other projects: https://twitter.com/MarcoWorms/status/1646283730057568257
- this article https://hackmd.io/FEUufpxRRWyZg7GbaTnJ-Q that is about yearn+ledger need work from me to be published, will aim to publish it by the end of next week

**Comment by MarcoWorms** [comment]
- ypriceapi
  - tutorial: https://hackmd.io/tYsgIt4kQ82S-wjyGZyiYg
  - docs with example requests fr many languages:  https://hackmd.io/Tw1l_-02QROkw-BeKD-ByA

- how to integrate v3 vaults in partner website, redirecting funds to get the partner fees
  - https://hackmd.io/i9PsdYiNTSWBrATdeDxQXQ

**Comment by MarcoWorms** [comment]
- been structuring a way with draper to help him scale up his creative process, right now we are doing a test where I'm helping him come up with the briefing for yETH bootstrapping campaign and we'll see how else can I help as we deliver stuff together
- working on a webapp version of yip generator and validator
  - https://github.com/MarcoWorms/yip-toolkit
- about the v3 docs mentioned past reports, still editing this one: https://hackmd.io/i9PsdYiNTSWBrATdeDxQXQ
- ypriceAPI FE seems to be ok, doing a status page with bob now https://ypriceapi.vercel.app/status

on the documentation side, both ypriceapi and the v3 docs I'm working on I'm testing flows using autogenerated docs by gpt4 and doing a final retouch, because of the 8k tokens API most relevant context + query + answer fits within the same query and I think it can help us makes good docs much faster, for example ypriceAPI is generated on top of the API openapi.json spec and it was able to make examples for many languages, v3 docs followed a similar pattern but I used contract ABI, and the fun thing was that after doing a first review with schlag I was able to just throw all his feedback into gpt4 to fix the text wherever needed and it seems to have worked very well

**Comment by MarcoWorms** [comment]
will write a more extensive report soon on all ongoing things, but just registering some stuff:

- still on more docs for v3 besides what's queued (https://github.com/yearn/yearn-devdocs/pull/291) in github devdocs
- working on draft article for yAudit: https://hackmd.io/kTTYCMI7SZqqLWWcGvf1cw
- been exploring aroung GPT + Apework to see if we can have an agent that interacts with the chain, so far I'm coming up with an article that helps replace brownie with ape for contract deploiyment and interaction, can become more stuff in the future: https://hackmd.io/_mp0OTZCQuKCLuXnFYlxSQ
- merged 2 older projects into a webapp: https://yip-toolkit.vercel.app/
  - ![image](https://user-images.githubusercontent.com/7863230/236555984-e74d1404-236e-4e03-b92f-21236b1ad557.png)

**Comment by MarcoWorms** [comment]
- I am handling the flow to replicate twitter announcements into other socials like discord and telegram channels (handed over from ghosty)
- syncing with wavey for ybal docs, updated ycrv docs: https://github.com/yearn/yearn-devdocs/pull/328
- writing a piece for yaudit, waiting for a first review with someone from there to see if the direction makes sense: https://hackmd.io/kTTYCMI7SZqqLWWcGvf1cw
- working with draper on future comms for socials (no spoilers hehe)
- I should send my budget renew request by monday, will do a write up on what worked and what didnt the past 3 months and what I want to focus on the next ones
- updating our docs about zapping, stuck on some UI stuff but major is helping me unstuck where needed: https://github.com/yearn/yearn-devdocs/pull/327
