### ISSUE TITLE
Budget Request: yETH Team

### ISSUE THREAD

**Issue by 0xPickles** [yearn/budget#131]
## Scope

Following the individual requests to investigate (#107) and implement (#114) yETH, and the adoption of [YIP-72](https://snapshot.org/#/veyfi.eth/proposal/0x8969cde98d5d8a7be745e442a3288ce0cf3b35bf99ab72265f66c96d117a0f78), it is now time to prepare, deploy, bootstrap, and launch yETH.

This request establishes a yETH Team with the goal of supporting and facilitating the function and adoption of the independent protocol, governed by st-yETH token holders.

## Plan

Deliverables include:
* [ ] Completing security audits for relevant codebases.
* [ ] Implementing the specification as laid out in YIP-72.
* [ ] Planning and preparing for a bootstrapping phase (leading into a launch) in June, including preliminary first iterations of complimentary functionality that is independent and non-critical for the use of the protocol, such as an interface, documentation, growth hacking, and online communications.

## Deadline

May 2023

## People
* @0xkorin
* @0xpickles 

With additional support from the following "team prospects", who will be considered for promotion to full team members as their contributions grow:
* corn
* draper
* evan
* marco
* major
* wavey

## Funding

We request funding in the form of:

1. **Contributor grants** for contributors.
   - Paid for work to fulfill the deliverables of the above plan.
   - Paid in DAI and/or YFI.
   - Llamapay streams
2. **Security audit** of the bootstrapping contracts. Slot locked in for end of May, with a quote.

:::info
The goal is to have a plan for receiving long term sustainable funding secured by the end of the request period.
:::

## Amount

| Component | Breakdown | Amount |
|---|---|--:|
| Contributor grants | <ul><li>0xkorin: 15k DAI + 1.5 YFI</li><li>0xPickles: 5k DAI + 0 YFI</li><li> Additional contributors: 3 YFI</li></ul> | 20k DAI <br>4.5 YFI |
| Security audit      | Slot locked in for end of May, with an accepted quote | 25k DAI           |

## Wallet Address

* 3 of 5 Gnosis Safe that will be provided to yBudget separately

## Reporting

Once, at the end of the request period

## Contribute

New contributors are welcome to participate through joining this Telegram group: https://t.me/+VTjZKCzPkLhmYWFkz

**Comment by visitskyworld** [comment]
@0xPickles I am interested in this project and want to contribute.
