### ISSUE TITLE
Fund the Frontend Team

### ISSUE THREAD

**Issue by saltyfacu** [yearn/budget#70]
### Scope

The frontend team has a series of projects under maintenance, others in active development, and some new projects to start. The scope of this request is to maintain the currently finished UI projects, continue improving the projects under active development, and start a new project called NFTreasury.

Below there's a list of the projects under the frontend team.

#### Done / Low Maintenance
- yearn-issues
- ape.tax
- yBuybacks
- Yearn comms
- Vaults at Yearn
- yHack
- YFI experience
- yDataSync

#### Under active development
- Web lib
- Yearn SDK
- yearn.watch
- yearn.finance

#### New
- NFTreasury
- B2B Dashboard

### Plan

The plan is to focus on the projects under development and NFTreasury. Yearn.watch is the main priority among the active projects. We will continue to improve its reliability. The lead YW developer has a previous grant. The team will fund additional contributors via bounties, using part of this grant.

The budget will only cover this month. We will reassess after the deadline and submit another request that is in line with the requirements of the team.

We don't want to do streams yet, but to send the funds to contributors at the end of the month. We will leverage bounties for small tasks. All the details will be shared in comments at the end of the month.

### Deadline

2022-06-30

### People

Gambito: senior dev leading some of the projects
Major: senior dev leading some of the projects
saltyfacu: helping out with the organizational part
Chef: UI dev
Marco Worms: UI dev will take care of NFTreasury

Other freelancers via bounties

### Money

We plan to distribute a grant for each person in charge of a project and use bounties to fund other contributions linked to projects in maintenance mode or isolated contributions.

### Amount

25000 DAI

### Wallet address

0x0

### Reporting

- [X] I agree to post weekly updates

**Comment by MarcoWorms** [comment]
In the last episode of weekly report:

> I think by the next week most of the app should be functional!

aka

![image](https://user-images.githubusercontent.com/7863230/175577486-c3b777c4-31f5-45d8-be16-8ea76bba5083.png)

My ingenuous self thought that interacting with contract was as easy as going to etherscan and pressing some buttons, turns out that applying the correct practices, debugging blockchains locally, and using our web-lib abstractions has a much steeper learning curve than I thought initially, so I asked for help to Major and we decided I will focus on UI elements while he will bootstrap the contract interactions (and we review each other stuff) because this division will be the best for optimizing to the project's "fast" delivery.

We also had some issues with "designed screen VS reality" and we raised them to the people helping out with design and product.

So we don't have a functional app this week, although many PRs were made to refactor some UI components and add initial web3 context! A list of PRs here would be cumbersome but it can all be followed at https://github.com/Majorfi/NFTreasury/pulls and the latest build is always at https://nft-reasury.vercel.app/ (please don't sign any transactions yet, it's still being built and might result in lost funds if tested in prod right now)

I will work on until the next report in the responsive version, it's not contemplated in the initial design but since we are waiting on some things to advance the web3 parts I think it will be nice to make it fully responsive for proper mobile usage

**Comment by MarcoWorms** [comment]
## NFTreasury

This week we had great progress on the app!

Livre preview: https://nft-reasury.vercel.app/ 

* app is now fully responsive, all screens fit on mobile properly!
* web3 interactions are working properly (exception: `withdraw` still doesn't work, but you don't need this one to test the entire flow)
* all page components are done (exceptions: daily earnings graph and estimates)

I'm currently working on making the graph work, the app is functional right now (for the "happy path") and we should fix the exceptions and quirks by next week,

**Comment by saltyfacu** [comment]
Please send from the budget:
- 2500 DAI to `0xB1d693B77232D88a3C9467eD5619FfE79E80BCCc` 
- 250 DAI to `0x8CCc50Abf345f4CF5477F2E244DC33F7F0C5579E`

**Comment by MarcoWorms** [comment]
## NFTreasury

The app is live and we posted about it on social media! All issues from past week were fixed I also made a quick making-off thread:

Live Link: https://nftreasury.org/
Yearn twitter thread: https://twitter.com/iearnfinance/status/1544408057152782338
Making-off twitter thread: https://twitter.com/MarcoWorms/status/1544430842302316544

I started working on the web-lib docs this week, added a page for a context and I intend to add more pages over this weekend:

- https://github.com/yearn/web-lib/pull/49

**Comment by MarcoWorms** [comment]
## Web-Lib

This week I started helping with web-lib docs:

 * https://github.com/yearn/web-lib/pull/50

And I'm also assisting Major in adapting the YFU repo for future projects usage by moving it from JS to TS and implementing the web-lib:

* https://github.com/Majorfi/yFu/pull/1

Also we had the merge of the UI forking guide with macarena finance so I made a twitter post for it (thanks banteg for the rt, it brings tons of engagement):

* https://twitter.com/MarcoWorms/status/1546989801567670274

**Comment by MarcoWorms** [comment]
## yFu

This week I worked on porting yFu repo to typescript + add web-lib to it. We are gonna use this same website for claiming comic nfts, this task is now done and the repo is now in TS and web3 enabled!

- https://github.com/Majorfi/yFu/pull/1

So I started making the claiming UI:

- https://github.com/Majorfi/yFu/pull/2

**Comment by MarcoWorms** [comment]
# yFu

The claim UI is OK, will be further polished but it's functional and connecting with the user's wallet using yearn's web-lib, what we need to do now is create the campaign at project galaxy and make the claim button hit their API to claim the NFT

Here are the screenshots of the current UI connecting the wallet:
<img width="1680" alt="Screen Shot 2022-07-29 at 4 53 16 PM" src="https://user-images.githubusercontent.com/7863230/181834115-990ca29a-8063-4edb-9439-d47f24e59fc7.png">
<img width="1680" alt="Screen Shot 2022-07-29 at 4 53 07 PM" src="https://user-images.githubusercontent.com/7863230/181834130-73c82175-65ce-480f-b166-bebc23d9ddf4.png">

**Comment by xgambitox** [comment]
Please send from this budget the following grants to contributors who have helped out in the past month of July:
- 2530 DAI to `0xB1d693B77232D88a3C9467eD5619FfE79E80BCCc` for contributions in NFTreasury, Web-Lib and yFU Temple
- 1250 DAI to `0x8CCc50Abf345f4CF5477F2E244DC33F7F0C5579E` for contributions in components and UI polish for veYFI
- 60 DAI to `0x9E63B020ae098E73cF201EE1357EDc72DFEaA518` for contributions in Testing/Deploying/Domains in yearn projects

Thanks all 💙

**Comment by MarcoWorms** [comment]
## yFu

This week I've dived into what needs to be done for this project with zemm, we decided that we will make our own NFT minting contract with openzeppelin instead of using Project Galaxy since we won't use any special feature they provide, my idea is to have a demo running in Fantom next week so we can test out clicking stuff "in prod" and then we remake the environment on ETH for real prod

**Comment by MarcoWorms** [comment]
## yFu

The contract for NFT emission is "done" but it needs reviews, I'm trying to find some peers to take a look at this repo: https://github.com/MarcoWorms/yfu-contracts

I think the contract review is the largest bottleneck, I will work on making the yfu-temple website call the contract functions next week and most things are set for release :)

**Comment by MarcoWorms** [comment]
## yFu

The contract I did is still under review, I applied some peer review requests from Major:

- https://github.com/MarcoWorms/yfu-contracts/pull/6

## Others

I picked up to do the draft screen for https://twitter.com/keshxyz/status/1559033713857626117?s=21&t=pWivQ6GZA9DcfI3IoUoZPQ

BobTheBuilder said we has P&L data on an [extension](https://github.com/BobTheBuidler/yrs-backend) of yearn-exporter, so I'm gonna run both locally (and see if I can improve the installation docs with any implicit info)

**Comment by DarkGhost7** [comment]
@MarcoWorms Thanks for the great updates here

**Comment by MarcoWorms** [comment]
## yearn-vault-descriptions

This PR had a couple come and go's but it's now on final review stages, it updates vault-descriptions repo with the networks we didn't have (op and arb)

- https://github.com/yearn/yearn-vaults-descriptions/pull/67

## web-lib

Made the docs for all util functions, now working on completing last details and make it consistent with docs from other folders

- https://github.com/yearn/web-lib/pull/77

## yFu

The contract I did is still under review, Zemm found some yAcademy members willing to make a community peer review on the contract:

- https://github.com/MarcoWorms/yfu-contracts

Also until next week I will make a complimentary system to the yfu website that will be a form collecting minters addresses and keeping them safe (I'll probably use google forms + google drive)  so we can ship the comic to them when it's done

## Others

I did not do anything around that draft screen I mentioned last week but I should do what I've mentioned until the next one!

**Comment by 0xMirim** [comment]
This was my first month contributing to Yearn. I basically just jumped in and started submitting pull requests and reviewing code. This ended up being a good strategy to learn the repos / tech stack we use. I'm now more integrated with the front-end team (who have been amazing supporting my efforts) and am working to re-focus on higher priority yearn projects and tasks. Below is an overview of what I accomplished this month. 

## yearn-vault-descriptions

I'd say most of my effort this month went into the vault-descriptions repo. I took on on the task of migrating it to Typescript, and generally improving the codebase where I saw opportunities to do so. I also learned a good bit about yDaemon in the process and am planning to expand my efforts to contribute to that repo as well.

- https://github.com/yearn/yearn-vaults-descriptions/pull/61
  - Also integrated web-lib, removed unused code, and resolved warnings in addition to migration
- https://github.com/yearn/yearn-vaults-descriptions/pull/69
  - Also removed 3 unused API Routes
- https://github.com/yearn/yearn-vaults-descriptions/pull/60
- https://github.com/yearn/yearn-vaults-descriptions/pull/70
- https://github.com/yearn/yearn-vaults-descriptions/pull/72
- https://github.com/yearn/yearn-vaults-descriptions/pull/71
- https://github.com/yearn/yearn-vaults-descriptions/pull/58
- https://github.com/yearn/yearn-vaults-descriptions/pull/74


## yearn-press-kit
- https://github.com/yearn/yearn-press-kit/pull/28
  - Also discovered an issue causing toasts to not be shown properly, which Major was able to resolve quickly
- https://github.com/yearn/yearn-press-kit/pull/24
- https://github.com/yearn/yearn-press-kit/issues/26
- https://github.com/yearn/yearn-press-kit/pull/25
- https://github.com/yearn/yearn-press-kit/pull/21


## web-template
- https://github.com/yearn/web-template/pull/53
- https://github.com/yearn/web-template/pull/54


## ySync
- https://github.com/yearn/ySync/pull/47


## Code Review

I occasionally take the time to review / comment on pending pull requests if I have an understanding of the repo or if I feel that I can provide value. The reviews don't always find issues but sometimes they do uncover potential improvements which I document and share. 

- https://github.com/yearn/yearn-vaults-descriptions/pull/67#issuecomment-1220860904
- https://github.com/yearn/yearn-vaults-descriptions/pull/66#pullrequestreview-1078341841
- https://github.com/yearn/yearn-devdocs/pull/231#pullrequestreview-1073503107
- https://github.com/yearn/yearn-devdocs/pull/235#pullrequestreview-1072970541

**Comment by ktgnova** [comment]
Hello! Here is my first report. 

## yearn-press-kit
I started contributing to Yearn a few weeks ago. The first thing I did was learn the stack/docs and work on yearn-press-kit.
- https://github.com/yearn/yearn-press-kit/pull/9 

## web-template / web-lib
Then switched to a series of tasks to implement a new design system into web-template. In this case, it has to be done through web-lib. As of now, this one is still a work in progress so you might see it in the next report as well.
- https://github.com/yearn/web-lib/pull/78

**Comment by MarcoWorms** [comment]
## web-lib

- https://github.com/yearn/web-lib/pull/77
Finished adding the first utils docs

## yFu

There are 2 things that needs to be done to put this in production:

1) Academy is helping us review the contract, I joined a discord with them this week and they started to take a look at it and we are chatting over there (Zemm is included). Once this is done we need to connect the frontend with the contract (the simplest part)

2) We need to setup a page that once the person has the NFT he/she can answer a form with the receiving physical address + wallet address (so we can validate payment)

**Comment by saltyfacu** [comment]
Please send from this budget the following grants to contributors who have helped out in the past month of August:

0xMirim -> 0x50F56B90a39219c534fa2F2e7A6758D3b182F9A4: 3000 DAI
Marco -> 0xB1d693B77232D88a3C9467eD5619FfE79E80BCCc: 2500 DAI
Nova -> 0xC1109238D925CFb355394F2055ab4f6c5732ceC0: 1500 DAI
Chef -> 0x8CCc50Abf345f4CF5477F2E244DC33F7F0C5579E : 2500 DAI

**Comment by MarcoWorms** [comment]
## yDaemon

I wrote an article about what yDaemon does and how to run it locally, I talked with major and I should work this week on improving the yDaemon docs itself now since it has some undocumented things and "TODOs" laying around

## yFu

Last week report still counts, this week I'm working on point 1 which is the contract review, Academy sent their audit review this week and I should change some things on the contract

## Exporter + Trx History screen

- I talked with Kesh (the screen designer) to clarify some points about the design and layout, I was able to run the yearn-exporter and I intend to start working on the screen now on top of this https://github.com/BobTheBuidler/yrs-backend (bobthebuilder is helping me a lot on this one!)

**Comment by ktgnova** [comment]
This month has been crazy but I worked on implementing the design system to web-lib and did research, trial and error, and figuring out how things work under the web-lib hood. I need to spend more time with it and I will continue this work next month.

[https://github.com/yearn/web-lib/pull/78](https://github.com/yearn/web-lib/pull/78)
