### ISSUE TITLE
New Written Content and Improvement of "Using Yearn" Section 

### ISSUE THREAD

**Issue by JKtranslator** [yearn/budget#71]
### Scope

To update the "Using Yearn" Section of Yearn Docs and to write new content

### Plan

1. Updating the “Using Yearn” section of docs

Rationale: While the content is good, this section doesn’t give all information needed for the user to interact/navigate the website, as a lot has changed.

Proposal:

To break the docs into different pages (the same ones on the website), with each one explaining in detail what can be done inside of it:
Landing/Portfolio
Vaults
Labs
Iron Bank
Settings

Each section will have short gifs showing how to interact with the page’s components. 
![yearn finance](https://user-images.githubusercontent.com/88235023/173156884-2fc8cae1-a85e-4b3f-947d-c0905675c253.gif)

2. Content Writing

Rationale: To write data-driven content with an informative explanation about yearn.

2.1 A piece explaining the evolution of yVaults to explain/highlight past performance
To the users (retail or not), the USDC Vault is where he deposits USDC. They don’t know that there were
 v0.2.2, v0.3.5, etc., versions and that the metrics shown on the website now are related to the latest version.

![Image 3](https://user-images.githubusercontent.com/88235023/173157640-46383c39-f2b1-43cc-b7bf-191ebefba41e.png)

APY at the website
![Image 4](https://user-images.githubusercontent.com/88235023/173157712-bccb2161-57d2-4d3d-a52b-36e1038a8217.png)

Current vault
![Image 5](https://user-images.githubusercontent.com/88235023/173157777-07e5df93-a8fa-4c34-9020-c73ad68bb90c.png)

But the 0.3.0 version still has/had assets on it that were routed to the 0.4.3

![Image 6](https://user-images.githubusercontent.com/88235023/173157983-2207d400-877e-4e2b-ab71-a40828f8c6e2.png)

So, the idea is to provide a visualization like the one below for all v2 yVaults to retrieve their historical results beginning on the first version.

![Image 1](https://user-images.githubusercontent.com/88235023/173157407-6bbea1bb-4a29-4a9d-bd8f-276ea901bb72.png)

data source: Yearn vision

2.2 Building upon the previous one, the idea now is to provide a comparison with Compound, using the share price evolution of the yVault vs. the equivalent cTOKEN + COMP rewards.
![Image 2](https://user-images.githubusercontent.com/88235023/173157486-c3a73a3e-f131-47d1-9950-7620ee57f375.png)

The idea is to show that using yearn as a “set and forget” investment is better than providing the underlying asset directly to Compound itself.
2.3 A “Yearn in number” monthly recap in the same fashion as the previous one: https://twitter.com/jameskbh/status/1532863770527244288?s=20&t=oqfylYmNhbWyEa-89FxhDw

### Deadline

2022-06-30

### People

jameskbh

### Money

A grant to perform the tasks mentioned before.

### Amount

1000 DAI

### Wallet address

0x714D8b5874b3a6a69f289f4e857F4C9670074296

### Reporting

- [X] I agree to post weekly updates

**Comment by milkyklim** [comment]
Website related docs are out of scope, right now. Main reason – there is discussion to switch to Liquity UI model where multiple parties can host interfaces while Yearn works at them bottom smart-contract layer. 

As to Compound comparison, bowswap.finance provides similar feature during migrations. That should be sufficient for users.
