### ISSUE TITLE
Fund the yTranslation Team

### ISSUE THREAD

**Issue by qosmonot** [yearn/budget#73]
### Scope

This is a fixed grant request for the yTranslation Team. The idea is to continue with our work on translating the website, yearn-meta, & yearn-comms (Yearn Blog) repositories. Our contributors have made over 230 PRs on these above repos over the last 2 months.

With the new docs being re-done, it's important to continue to have a translation team ready.

New partners and users from all around the world will come from new partnerships. We need every piece of TVL we can get in this market. Having all the content available in different languages helps in this objective.

The translation team has been auto-sufficient and a fairly active group with fast response and the idea is to maintain the same energy and attitude, which makes it important to have part of Yearn´s budget allocated to this group. 

### Plan

The action plan is simple, the yTranslations team will continue translating and sharing yearn content in the same way it has for the past 5 months.

@DarkGhost7 will continue to guide the team about protocol priorities (new docs, etc.).

We will continue to prioritize time-sensitive translations (marketing-related content and newsletters).

### Deadline

This grant is for 3 months, finishing on August 31st

### People

The yTranslation team is composed of a dozen active contributors. Below are the people currently active and included in this grant request:

![image](https://user-images.githubusercontent.com/32738380/173523395-b7df6908-ba09-4c4c-b765-ff261e014736.png)

This fixed grant for the yTranslations team allows for any language or contributor to be added to the team without affecting the requested budget. 

note:

Cryptouf will continue being part of the team as an FR translator but he made an individual proposal so is not being included in this grant.

@qosmonot will continue to manage the yTranslations team, but also made an individual proposal, so is not being included in this grant.

We will establish a procedure for new translators for a minimum of translations needed to join the translations group. This is important not to show languages in the blog that don´t have enough content.

### Money

The requested grant, covering a period of three months, will be streamed to a multi-sig managed by members of the yTranslation team, and will be distributed monthly between the contributors and active members of yTranslations, through a point system that was developed within the team (allowing the funds to be split between the team members based on the amount of work each has completed during the epoch).

The previous epoch's spreadsheet can be found here: https://docs.google.com/spreadsheets/d/1sR8_nUM5UpL2yk0Yttc1AvOq0GcEb_rM-vQ3uwpf23U/

The aim here is to establish a fair grant so people are motivated to do the work with good quality and in a timely fashion (expected for most content, especially newsletters), but we know the importance of adjusting the expectations based on the actual market conditions.

Looking at the last three epochs of Coordinape (epochs 14, 15, 16), the average budget allocated to translations (incl. 12 translators, not including Cryptouf, qosmonot) was of 15k$ (see table below).

![image](https://user-images.githubusercontent.com/32738380/173523569-a77be083-675f-41c5-a262-c28078158775.png)

For this grant request, we propose a fixed budget, along with a 30% haircut, for a monthly amount of 10k $. The current request covers a period of 3 months, finishing in August.

### Amount

30,000 DAI

### Wallet address

0x0

### Reporting

- [X] I agree to post weekly updates

**Comment by milkyklim** [comment]
Pulled data for blog and main websites – main problem with translations is coverage. Yearn only gets ~2% users (per country) from non-english countries. 

That brings the question if translated articles are that useful for larger coverage. It’s good overall job but necessity is questionable, especially, with budgets cut. 

Stand is – it’s better to commission separate pieces when there is a decision to target specific audience.
