### ISSUE TITLE
Antiscam and other discord bots

### ISSUE THREAD

**Issue by danijelthales** [yearn/budget#74]
### Scope

Fight off discord scammers and add informational price discord bots 

### Plan

This is operating for longer than a year and the reason Yearn discord is a pleasant place to reside

### Deadline

2022-06-14

### People

Just myself

### Money

Funds are going towards hosting and dev costs . These are yearly costs, there wont be another request for next 12 months.

### Amount

1000 DAI

### Wallet address

https://etherscan.io/address/0x461783a831e6db52d68ba2f3194f6fd1e0087e04

### Reporting

- [X] I agree to post weekly updates

**Comment by kx9x** [comment]
I can vouch for danijelthales. The discord bot is clutch for keeping us scam free. $1000 for hosting and dev costs across 12 months seems like a fair price for the value it gives.

**Comment by vany365** [comment]
2nd kx9x. The price bots are nice but the antiscam bot literally protects our server from 99% of the spam/scam accounts out there. For a stability standpoint of our discord I believe this should be approved.
