### ISSUE TITLE
contributor: manage comms / yTranslations

### ISSUE THREAD

**Issue by qosmonot** [yearn/budget#75]
### Scope

Yearn needs to make it through this bear market. Dead or inactive communications channels would not send the correct message. We should make sure that communications and content are still being produced and visible.

I had previously contributed to the publication and maintenance of The Vaults at Yearn, and now work on the yearn-comms repo / blog.yearn.finance. I review translations and add English content to the blog while working with the yTranslations team.

This request will allow me to continue my work developing the blog, maintaining it and its translations, and leading the yTranslations team. 

### Plan

I will:

- maintain the comms repo (blog.yearn.finance), review, edit, and publish content in English and various translations (~100 PR reviews/month)
- continue to develop the blog product (designing and adding features)
- manage, consolidate, and lead the yTranslations team (12-20 contributors)
- manage and control the distribution of funds to yTranslations
- help proofread and review articles, helping with comms and marketing.

### Deadline

This grant is for 3 months, finishing end of August

### People

I am asking for a personal grant, to work on the blog/comms product. This is a cross-group product, that needs coordination between the yTranslations team, the marketing/content team, and front-end development (@Majorfi ).

### Money

I have been compensated through Coordinape since Epoch 1, 

With the Community circle halted, I am requesting this grant

For reference, below are my compensation details for the past 3 epochs on Coordinape (Community Circle):

- Epoch 16: received 171 / total 6353 GIVEs = 2.70%
- Epoch 15: received 191 / total 6337 GIVEs = 3.01%
- Epoch 14: received 199 / total 6945 GIVEs = 2.87%

I would like to request a grant of 1,000 DAI / month, for 3 months, subject to extension.

### Amount

3,000 DAI

### Wallet address

0x3D935C7bf3Ec8891C17b074b841d940264f073c5

### Reporting

- [X] I agree to post weekly updates

**Comment by DarkGhost7** [comment]
I support this proposal. @qosmonot has done a great job so far contributing to and helping with the translation team and the blog in general. He helped create blog.yearn.finance and has been helping to maintain it as well.

**Comment by RestlessMike** [comment]
Qosmonot is a hard-working and proactive project manager that we shouldn't let go, I support this proposal and to continue to have great professionals onboard.

**Comment by qosmonot** [comment]
@milkyklim Agreed, I have adjusted the proposal from 6,000 DAI across 3 months to 3,000 DAI.
