### ISSUE TITLE
Fund the ySupport team

### ISSUE THREAD

**Issue by kx9x** [yearn/budget#76]
### Scope

ySupport represents a group of Yearn moderators across Discord, Telegram, and Reddit who are the first responders for user issues, community builders, town criers, and educators for those who are new to DeFi and Yearn. 

The folks in ySupport are always there to support the users, be it helping folks deposit into a vault, teaching someone how an approval works, or guiding a user how to use Etherscan to initiate a transaction when the Web UI is wonky. Furthermore, they keep our community tightknit during the quieter times, whether that is engaging with the community with memes or helping Yearn host some of the most compelling discussions you can find in a crypto Discord. 

This cohort of folks represent a group of long-time Yearn contributors, veterans of our Coordinape compensation system. The ySupport team has a proven track record and as a long-time contributor myself, I believe in funding ySupport for their impact with our users.

### Plan

The action plan for ySupport for this quarter is engagement with the community, upselling Yearn to new users, providing critical user support, triaging issues to the development team, and making Yearn the most attractive Discord/Telegram/Reddit community in crypto.

We see the bear market as an opportunity to build stronger positivity in the community. FUD is rampant during these times, but it is important that we stay optimistic in our channels and build up Yearns brand as the safest, most stable place to earn yield no matter the market conditions.

### Deadline

2022-08-31

### People

List of ySupportoooors to be eligible for payments:
- crolev
- jyhelper 
- arberx
- oldfrog
- pp
- fugggginoooob
- vany

Multisig signers (4 of 5):
- crolev
- jyhelper
- vany
- kx9x*
- dark ghosty*

*kx9x and dark ghosty are not eligible for payment, just helping with multisig signing

Note: we have 4 of 5 so each quorum includes one person not being paid (i.e. kx9x or dark ghosty).

### Money

Our current plans are to use all of the funds on a Coordinape-style monthly disbursement, where we vote based on impact for the given month.

~~$12,000~~ $10,000  a month across 7 ySupport staff represents about ~~$1714~~ $1428 per person a month. This helps us keep a similar amount of budget spent on support in previous Coordinape cycles, while also factoring in broader push to tighten budget overall.

### Amount

~~36000~~ 30000

### Wallet address

0xbd7B3Bc2C4581Fd173362c830AE45fB9506B3dA5

### Reporting

- [X] I agree to post weekly updates

**Comment by DarkGhost7** [comment]
The support team has been great and I consistently hear that Yearn has great and fast response/support from both our telegram and discord support channels. I support this proposal for funding the ySupport team.

**Comment by Faolain** [comment]
The support team has done and continues to do a herculean effort which few if any other projects can match. At the risk of sounding like a shill (but I am for ySupport) they work tirelessly answering questions from the most basic to those quite advanced providing legitimacy to Yearn in spite of market turbulence/FUD. Beyond that I've also seen first hand the value the team brings in surfacing issues seen by general users for the dev team. Cultivating an engaged & informed community is paramount and I'm confident in this team to continuing carrying out their duties.

**Comment by RestlessMike** [comment]
Losing such a great, knowledgeable and dedicated team as ySupport would be one the most significant losses of this bera. We need to fund these guys and continue building IMO.

**Comment by milkyklim** [comment]
Would you mind changing the amount to 30 000? Generally, important one to approve but yearn is planning to make larger cuts internally, too.
