### ISSUE TITLE
[Team] DATA Analytics Q3 Funding

### ISSUE THREAD

**Issue by bluewillow870** [yearn/budget#87]
### Scope

The purpose of this request is to fund the DATA Analytics team's work for the next three months.  

The DATA Analytics team in Q2 focused on 1) net-new product development (risk score & metrics framework and API), 2) R&D into updating APY calculations, gas fee optimization, and automating YFI buybacks, and lastly dashboard development to support TVL and partner analysis.

> _Summary of completed work: https://github.com/yearn/yearn-data-analytics_

In Q3 (July - September '22), the team will continue to support data engineering efforts (eg./ enhancing exporter data pipeline and infrastructure), dashboard development (e.g./ partner dashboard), partnering with other teams like yearn watch and front-end on API development. 

As the team continues to mature, we will become more efficient at creating insights, finding patterns and proactively collaborating with other teams across yearn. Being able to take advantage of big data puts yearn ahead of its competitors with the right knowledge and insights, which leads to higher profits. A core data culture cross-team  allows everyone to have a common understanding of what data is available and how it can be used to drive decisions. 

> While the vault management team is also focused on dashboard development and analytics, our area of focus is complimentary and we intend to collaborate with that team on some of the projects listed below. 

The team currently consists of 3 data engineers, one analyst/PM as well as contributors completing one-off bounties.

### Plan

Areas of Focus:

- **Data Engineering**: Supporting platform stability and data access. We will work with exporter leads to ensure data pipelines are running and that information is easily accessible. We will also prepare existing and net new data for consumption as needed and drive automation efforts. 
- **Analytics/BI/Reporting**: Taking information in the various data repos and using it to create interactive charts and dashboards for various stakeholders to use in reporting and diagnostic investigations. Building analytics capabilities to uncover customer, product, and operational insights
- **Data Science**: Extending existing products through features like search, recommendation or matching algorithms. 
- **Growth/R&D**: [Develop POCs for new data products](https://docs.google.com/spreadsheets/d/1mBdVB7TkfVCFnS7BgR_Qo4FxD2cK6PELk9jIgFeTq60/htmlview#gid=1008312346). Analyzing data sources and proposing solutions to strategic problems/opportunities.

**Active Q3 Projects:** 

- **Centralized exporter db**: Replacing Victoria db with Postgres timescale db to unify data into one database.
- **Risk Framework**: Maintain and update the strategy scores for the risk framework
- **API Development** (add exposed exporter endpoints to api.staging.yearn.vision, help integrate and migrate the risk api to major's new api (api.ycorpo.com), explore integrating -**R&D**: Collaborate with [Messari](https://github.com/messari/subgraphs) to build new data products using their subgraph/on-chain data,
- **Backtester**: Backtest ssb strats on historical data and calculate how much people would earn/lose taking into account curve pool state over given period of time
- **Partner/B2B Dashboard Data Infra**: Supporting data engineering efforts needed to building this dashboard
- **Automation**: Support automation efforts to reduce manual workstreams strategists are driving
- **Subgraph Support**: ongoing work to support subgraph on chain data analysis

> _**Additional projects that span dashboard development, data science and new product development are still being scoped for Q3._ 

-  

### Deadline

2022-10-01

### People

**Core team + responsibilities**

_we have no leader but we have included the roles and responsibilities of current team members here:_

- borrito: **Top Dog** 
-- data engineer, data scientist and quantitative financial analyst 
- huggingbot: **Data Whisperer** 
-- data engineer and front end developer
- farrah:  **Idea Alchemist** 
--_not receiving remuneration from this grant_ 
--data analyst, product development, organizational efforts
- bobthebuilder: **Wizard of Light Bulb Moments** 
-- _not receiving remuneration from this grant_ 
-- Subject matter expert on data infra and exporter
- marius:  **Exporter and DevOps Overlord**
-- _not receiving remuneration from this grant_ 
-- Subject matter expert on data infra and exporter

**Additional Contributors**

One off bounties will be issued to contributors working on ad-hoc projects. 

**July Allocation of Funds:**

- 6,000 : borrito
- 3,000 : huggingbot
- 3,000 : kofee

### Money

Funding will be streamed to the team members noted above as well as contributors supporting projects within the data analytics team's portfolio. We are requesting 10-12k per month for the next three months. 

### Amount

12000

### Wallet address

streamed to contributors

### Reporting

- [X] I agree to post weekly updates

**Comment by 0x7171** [comment]
Thanks for the request @bluewillow870, I have some follow up questions: 

1. How does `kofee` fit into this budget request? I see they are allocated 25% of the requested funds but are not mentioned in the team?

2. What's the period of the request? The title and the description suggests it's for the entire Q3, but "July allocation of funds" seems to allocate 100% of the amount for the first month of Q3. Could you advise?

3. You write `One off bounties will be issued to contributors working on ad-hoc projects`. At the same time 100% of funds seems to be allocated to 3 contributors. How will you be funding the one off bounties?

**Comment by bluewillow870** [comment]
Thanks for reviewing the request and for the thoughtful questions. 

_1- How does kofee fit into this budget request?_ Each month the team will issue bounties to contributors working on a one- off projects. Kofee is one of those contributors driving the following Q3 project: "Centralized exporter db: Replacing Victoria db with Postgres timescale db to unify data into one database."_ It is important to note that this request is to fund the data team for the next three months, however the amount each month will range between 9-12k max depending on contributors outside of the core team working on key projects.

2- _What's the period of the request? The title and the description suggests it's for the entire Q3, but "July allocation of funds" seems to allocate 100% of the amount for the first month of Q3. Could you advise?_ This request is to fund the data team for the next three months, however the amount each month will range between 9-12k max depending on contributors outside of the core team working on key projects. Borrito and hugginbot will receive 9k combined per month for the next three months and we are budgeting an additional 3k for bounties. If the budget team prefers, we can submit a separate request each month. 

3- _You write One off bounties will be issued to contributors working on ad-hoc projects. At the same time 100% of funds seems to be allocated to 3 contributors. How will you be funding the one off bounties?_ Please see responses to the previous questions.
