### ISSUE TITLE
Data Visualizations for Yearn

### ISSUE THREAD

**Issue by kyhoon** [yearn/budget#89]
### Scope

Data visualizations have become a powerful tool to convey one's message on social media, especially in the DeFi space during this bearish market full of fear, uncertainty, and doubt.

* [Token Terminal tweets about Polygon](https://twitter.com/tokenterminal/status/1563899946432188416?s=20&t=58jmDVNhmqJ1FAX35OZCCw)
* [Uniswap Labs tweets about the ETH/USDC pool liquidity](https://twitter.com/Uniswap/status/1559621941903990784?s=20&t=n-iobLL6MFOEZhLLruk8nQ)

The above tweets are presented as an objective depiction of the market phenomenon and thus appear trustworthy, while being able to naturally ignite a value proposition from the community:

* [RT of the Token Terminal tweet](https://twitter.com/_khanhamzah/status/1563930855181107200?s=20&t=58jmDVNhmqJ1FAX35OZCCw)
* [RT of the Uniswap Labs tweet](https://twitter.com/hasufl/status/1559799638886170625?s=20&t=DDrSg1qZkviwLJJTxUNb2Q)

Yearn has a very powerful data infrastructure to create these narratives, visualizations that portray our main strengths and empower our branding. We already have a huge list of projects that are dedicated to create and persist our data. Just to name a few:
* [Yearn Exporter](https://github.com/yearn/yearn-exporter)
* [Yearn Vaults V2 Subgraph](https://github.com/yearn/yearn-vaults-v2-subgraph)
* [yDaemon](https://github.com/yearn/ydaemon)
* [Yearn DATA Analytics](https://github.com/yearn/yearn-DATA-Analytics)

However when we searched for [Yearn Finance on twitter](https://twitter.com/search?q=yearn%20finance&src=typed_query&f=top) we could not find a single narrative that was data-driven.

We want to fix this. 

### Plan

[The previous budget request for the data team](https://github.com/yearn/budget/issues/87) already contains the initiatives and the ongoing projects as a whole team, thus we would like to focus on the plans for this specific project here.

We plan to solve the above problem in two ways, creating the visualizations ourselves, and promoting the narratives created from the others. For the latter we believe that it is necessary to make a server that can embed and update visualizations created from different data platforms, such as [Dune Analytics](https://dune.com/browse/dashboards?q=yearn) and [Footprint Analytics](https://www.footprint.network/search?q=yearn&model=all).

We plan to update all visualizations in a weekly basis using the latest data. The changes in the interpretations will be noted also in a weekly basis through the social media.

We expect this project to span a total of three months. However, we would like to note that we make this request to be supporting the project for the first month only, for better flexibility and assessment of the project. Nevertheless, we outline the full 3-month roadmap in the following.

**First Month (Requested Month)**

* Create a frontend server to embed the visualizations using [our web template](https://github.com/yearn/web-template)
    * Currently in progress at https://github.com/huggingbot/messari-frontier-web
* Create a visualization of the [efficient frontier](https://en.wikipedia.org/wiki/Efficient_frontier) of DeFi assets
    * Currently in progress at https://github.com/kyhoon/messari-frontier
    * Sample datapane at https://datapane.com/reports/W3DrWPk/defi-frontier/
    * Collaboration with [Messari Subgraphs](https://github.com/messari/subgraphs)
    * Aims to help answer the following questions:
        * How good are the Yearn vaults compared to the other protocols?
        * For which token/chain should new vaults be made?
        * Which new yield sources should the strategies tackle for XYZ vault?

Sample image for the efficient frontier
![](https://i.imgur.com/UQEUUCj.png)

**Second Month**

* Migrate the visualizations created by jameskbh to the frontend
    * To share a few:
        * [yVaults v2 Historical Overview](https://medium.com/@jameskbh/yvaults-v2-historical-overview-23a9a7db28a5)
        * [Yearn Vaults’ Stablecoins report: DAI, USDC, and USDT](https://medium.com/@jameskbh/yearn-vaults-stablecoins-report-dai-usdc-and-usdt-620dfc11c72f)
    * We expect more analyses to be done throughout the first month
* Create a visualization of our customers
    * Sample plot at https://chart-studio.plotly.com/~borrito/3/#/
    * Aims to help answer the following questions:
        * What other protocols do our clients use?
        * Were the recent withdrawals transitory?
        * How does the distribution of TVL for a single vault look like? 

Sample image for the customer clustering
![](https://i.imgur.com/vBkBkJ7.png)

**Third Month**

* Create more visualizations in other platforms, and/or migrate them to the frontend
    * [Dune Analytics](https://dune.com/browse/dashboards?q=yearn)
    * [Footprint Analytics](https://www.footprint.network/search?q=yearn&model=all)
    * Twitter
    * Reddit
* Simple keyword cluster and sentiment analysis for Yearn
    * Preliminary step for using heavier AI methods
    * Collect natural language data from Twitter and Reddit
    * Aims to help answer the following questions:
        * How do people think about Yearn?
        * Which narrative is the most powerful for Yearn's branding?
        * What do people feel different about Yearn compared to other protocols?

### Deadline

2022-09-30

### People

List of team members and the responsibilities:
* borrito
    * implement the efficient frontier
    * will be addressing all issues full-time 
* huggingbot
    * develop the frontend server
    * prepare migrations of the previous works from jameskbh
* kofee
    * implement and maintain data pipelines (subgraph, yearn-exporter, ydaemon)
* jameskbh
    * create visualizations in flourish studio using data from the yearn-exporter
    * research other data visualization platforms
* farrah (*not receiving remuneration from this grant*)
    * lead potential product developments from the visualizations
    * in charge of internal assessment of the performance and effectiveness of the project
* bobthebuilder (*not receiving remuneration from this grant*)
    * subject matter expert on data infrastructure
* marius (*not receiving remuneration from this grant*)
    * subject matter expert on data infrastructure

The members will continue to support the other initiatives mentioned in [the previous budget request for the data team](https://github.com/yearn/budget/issues/87) as well.

### Money

$15,000 for a single month. After a month another request will be presented to support the next milestones of the project.

The budget will be streamed to the members noted above.

### Amount

15000 DAI, or YFI of equivalent value

### Wallet address

streamed to the contributors

### Reporting

- [X] I agree to post weekly updates

**Comment by RestlessMike** [comment]
Great project. Lfg.

**Comment by kyhoon** [comment]
Update for the first week!

### The Aim for This Week

We spent most of our time preparing the new server and finishing off some housekeeping work in the data repo.
More specifically, before actually setting up the frontend, we worked for first shutting down the temporary risk API that was being deployed from the repo to make things simple.
This requires us to finish migrating the risk framework to yDaemon and updating the test logic in ySync.

Another focus for this week was to try out the whole process of publishing an article/tweet, tracking some user metrics, and doing follow-ups and RTs if necessary.
We tried to come up with a simple tweet like [this one from Wot_Is_Goin_On](https://twitter.com/Wot_Is_Goin_On/status/1477745127707840514?s=20&t=cf0JEeJBZv4HKzl1MOJheA), but could not finish in time, we are still choosing the metric to portray.

### What We Actually Did

* borrito
  * migrated the risk framework to yDaemon (https://github.com/yearn/ydaemon/pull/15) and updated ySync (https://github.com/yearn/ySync/pull/64)
  * worked with jameskbh on creating the first tweet (https://github.com/yearn/yearn-data-analytics/blob/feat/ydaemon/research/stablecoin_vision.py)
* huggingbot
  * researched the options and methods for hosting [Flourish](https://flourish.studio/)
  * worked on creating workflows (https://github.com/yearn/yearn-data-analytics/pull/90) for automatically updating the figures made by jameskbh (https://public.flourish.studio/story/1681802/)
* kofee
  * handled issues for yearn subgraphs (https://github.com/yearn/yearn-vaults-v2-subgraph/pull/181, https://github.com/yearn/yearn-vaults-v2-subgraph/pull/187)
  * worked on migrating the tvl allocation functionality of the temporary risk API to yDaemon
* jameskbh
  * created a walkthrough on how to recreate [the Yearn Vaults' Stablecoins Report](https://medium.com/@jameskbh/yearn-vaults-stablecoins-report-dai-usdc-and-usdt-620dfc11c72f) from yearn vision (https://docs.google.com/document/d/1gOwK0XrlUSArmncTq62njhPj8pG5GJ2e7boPRzHtABE)
  * worked on creating the first tweet, checked available channels and touchpoints

### Plans for Next Week

It seems we would need some more lead time before we can actually start on the efficient frontier.
kofee will mainly be handling the migrations necessary for this transition.
borrito and jameskbh will make a draft for the tweet and start posting on the media.
borrito and huggingbot will work on replicating [the Yearn Vaults' Stablecoins Report](https://medium.com/@jameskbh/yearn-vaults-stablecoins-report-dai-usdc-and-usdt-620dfc11c72f).

**Comment by kyhoon** [comment]
Update for the second week!

### The Aim for This Week

Our primary focus for this week was to try out a simple tweet and prepare the data pipelines for it.
In this process, we found that some metrics for the vaults/strategies that were directly fetched using multicall do not match with the metrics shown on yearn.vision and the subgraph. Thus we collaborated with the Vault Management team and the subject matter experts to understand the discrepancies.

The mismatches will be handled soon after we launch the initial version of the frontend and the weekly tweets. I would like to share some details about it here for the record:
* `totalGain` field is missing for some strategies in yearn.vision (https://github.com/yearn/yearn-exporter/issues/393)
* multiple days are missing from the `VaultDayData` in the Mainnet subgraph

### What We Actually Did

* borrito
  * worked with jameskbh on creating the first tweet (https://github.com/yearn/yearn-data-analytics/blob/feat/ydaemon/research/vaults_web3.py)
  * changed the data provider for the efficient frontier to DeFiLlama (https://cloud.datapane.com/reports/W3DrWPk/defi-frontier/)
* huggingbot
  * updated the workflows for uploading the figures made by jameskbh (https://github.com/yearn/yearn-data-analytics/pull/90)
  * added the [the Yearn Vaults' Stablecoins Report](https://medium.com/@jameskbh/yearn-vaults-stablecoins-report-dai-usdc-and-usdt-620dfc11c72f) to the frontend
* kofee
  * worked on migrating the tvl allocation functionality of the temporary risk API to yDaemon (https://github.com/yearn/ydaemon/pull/52)
* jameskbh
  * worked on creating the first tweet, run sanity checks for the new data pipelines by comparing different data sources
  * collected data for creating a flowchart tree diagram for Yearn assets, which will be similar to https://public.flourish.studio/visualisation/10687248/

### Plans for Next Week

We are set with the initial contents for the tweet - sharing the vaults that have the highest APY - and the channels to share it, which are the YFI Interns twitter account and the data-science workgroup in discord. We will go over the data for a few more days and post it on Tuesday the 27th.

We are also planning to spin up a development server for the frontend next week. [The Yearn Vaults' Stablecoins Report](https://medium.com/@jameskbh/yearn-vaults-stablecoins-report-dai-usdc-and-usdt-620dfc11c72f) and the draft for the efficient frontier will be hosted on the server. The efficient frontier visualization will be honed to deliver the right narrative, it seems like the current pipeline can show us only the distinction between the USD backed and the ETH backed pools.

**Comment by kyhoon** [comment]
Update for the third week!

### The Aim for This Week

Our main focus for this week was twofold: to create the initial draft for the efficient frontier visualization and to finally finish the migration of the previous FastAPI to yDaemon. The first item has been done, but the second item still needs confirmation from the consumers of this information, mainly the vault management team.

We also began to post tweets and schedule RTs using the YFI Interns twitter account. Although increasing the traction of our media channels was not the primary goal of this project, we thought it would be beneficial to increase our media frequency to get more feedback for our visualizations.

### What We Actually Did

* borrito
  * posted the first tweet with jameskbh (https://twitter.com/YFI_interns/status/1574752793738485763?s=20&t=CWroHudoQiNsWvWZX5tAGg)
  * created the draft for efficient frontier (https://cloud.datapane.com/reports/W3DrWPk/defi-frontier/)
  * finished off the migration with kofee (https://github.com/yearn/ydaemon/pull/67)
* huggingbot
  * researched the new monorepo structure for the [yearn-data-analytics](https://github.com/yearn/yearn-DATA-Analytics) repo
  * deployed the initial version of the frontend (https://messari-frontier-web-borrito.vercel.app/visualizations/flourish-studio/yvault-v2)
* kofee
  * worked on the yDaemon migration (https://github.com/yearn/ydaemon/pull/52)
  * temporarily shifted to work on the veYFI dashboard
* jameskbh
  * posted the first tweet, and scheduled RTs in the YFI Interns account (https://twitter.com/YFI_interns)
  * organized the different visualization platforms and contents into subtopics

### Plans for Next Week

We plan to change up the UI designs for the frontend to better match the looks of our visualizations, and hopefully also to blend into our [brand image](https://brand.yearn.finance/). The app will be hosted from the [yearn-data-analytics](https://github.com/yearn/yearn-DATA-Analytics) repo using the [Turborepo](https://turborepo.org/docs) system, which is the monorepo build system used by the [Yearn Web Lib](https://github.com/yearn/web-lib).

We also plan to continue the tweets about some basic information on our products like the APYs of vaults.

One thing to note is that some members of the team, kofee and huggingbot, will also be splitting their time to work on creating dashboards in yearn.vision for veYFI. This could temporarily decrease their contribution to this project, but we will make sure that we deliver the project on time.

**Comment by kyhoon** [comment]
Update for the fourth week!

### The Aim for This Week

We finally completed the migration and deployed the app at:
https://yearn-data-analytics.vercel.app/

![image](https://user-images.githubusercontent.com/30872891/194857848-64bf09e7-7848-4036-a51b-7cc00524a0af.png)

This initial version of the app will serve two visualizations, a [retouch of the overview of V2 vaults](https://yearn-data-analytics.vercel.app/visualizations/yearn-v2-vaults) made by jameskbh, and the [efficient frontier](https://yearn-data-analytics.vercel.app/visualizations/efficient-frontier). But the current visualizations are using outdated data points, which will be updated next week.


### What We Actually Did

* borrito
  * finished the migration of the data repo with huggingbot (https://github.com/yearn/yearn-data-analytics/pull/95)
  * made draft for the UI of the app (https://github.com/yearn/yearn-data-analytics/pull/96)
* huggingbot
  * finished the migration of the repo and cleanups (https://github.com/yearn/yearn-data-analytics/pull/95)
  * added monorepo structure to the repo (https://github.com/yearn/yearn-data-analytics/pull/97)
  * started working on the risk framework issues in ySync
* kofee
  * temporarily shifted to work on the veYFI dashboard
* jameskbh
  * worked on the descriptions for the visualizations (https://docs.google.com/document/d/1w0jYpGDqViCOwn4MkiySBPGGEJX6h16rBXUDRKOMQUA/edit?usp=sharing)
  * explored some potential product ideas related to the new visualization app (https://docs.google.com/spreadsheets/d/1Z6MPWS2uPtbLcGKIIzrcg32dIrxMYwXDzmDQo-PGz1g/edit#gid=0) 


### Plans for Next Week

Although there still remain some details that need to be handled, the big milestone for the first month has been completed. Thus we now plan to move on to the next milestone which is to implement the customer clustering analysis. We will create a separate budget request for this next round to continue the renumeration for the members.

Thanks to the retweet from the main account, the YFI Interns account is regaining back its traction. We will continue on making simple tweets about our vaults and strategies, and gradually move on to sharing simple visualizations like [the overview of V2 vaults](https://yearn-data-analytics.vercel.app/visualizations/yearn-v2-vaults). These tweets will have a link to the data visualization website and to our main yearn finance app to encourage traffic.

Marco Worms will help us out with the overall design and branding of the website, they have already created [examples for the assets and taglines](https://hackmd.io/QtLTN7keQk6SKDYVeoJUvw). We plan to work together on driving up the quality and giving some more character to the frontend.
