### ISSUE TITLE
Keep Maintaining Yearn Docs and Written Content

### ISSUE THREAD

**Issue by saltyfacu** [yearn/budget#90]
### Scope

This is a request to extend #69.

docs.yearn.finance is a key resource, also the Medium articles and other materials.

### Plan

The plan, as in #69, is to keep adding content to the docs and crafting new articles to onboard new users and highlight the main benefits of using Yearn.

I ask for a monthly grant for 3 months ending on November 31st. 5000 DAI per month during 3 months. The stream is already created, we only have to move the deadline. 

### Deadline

2022-11-31

### People

Marco Worms: technical writer
saltyfacu: helping out on the organization side

### Money

A grant for Marco to continue writing articles proactively and adding new content to the docs site.

### Amount

15000

### Wallet address

0xB1d693B77232D88a3C9467eD5619FfE79E80BCCc

### Reporting

- [X] I agree to post weekly updates

**Comment by MarcoWorms** [comment]
Helloo very nice to see this renewed <3

This week I worked on the yDaemon article which I already sent to farrah for review/publish:
- https://hackmd.io/M1S8JUgrR3uOa_QnRB7ezw

Also the strategy description glossary got published and I tried to make some social media awareness to it:
- https://twitter.com/MarcoWorms/status/1568092043016118272

Next things I'm working on:

- Article about this "how to write a strategy" talk that got added to the docs:
  -  https://github.com/yearn/yearn-devdocs/pull/241
- yDaemon docs (see #70)
- Article about history of yearn fee structure

**Comment by MarcoWorms** [comment]
Moved yDaemon article to medium and slotted for publication:

- https://medium.com/@marcoworms/ydaemon-one-api-to-unify-all-yearn-data-4fc74dc9a33b

Prepared the docs for veYFI launch, but might still need more reviews or be updated if new information comes up

- https://github.com/yearn/yearn-devdocs/pull/218

Working on updating partner docs to match new fee rules (some vaults have no mgmgt fee now!)

- https://github.com/yearn/yearn-devdocs/pull/243

And some minor fixes:

- https://github.com/yearn/yearn-devdocs/pull/242

**Comment by MarcoWorms** [comment]
Helped polish ycrv docs (unreleased)

- https://github.com/yearn/yearn-devdocs/pull/244

And finished the partners PR opened last week

- https://github.com/yearn/yearn-devdocs/pull/243

Waiting for the yDaemon article to publish on yearn socials, starting another one which is a bit larger scope than my normal articles but I hope the content quality makes it worth it, it's about applying the yearn risk framework on a personal level to analyze a defi investment strategy, draft: https://hackmd.io/Yng1EcThTeyLYm2iJR4FAA

**Comment by MarcoWorms** [comment]
Continued polishing yCRV docs, focused on this along with Draper and Wavey so we can ensure a smooth docs rollout:

- https://github.com/yearn/yearn-devdocs/pull/253

And for the current article I had great reviews from dark ghosty and storm so I had to restructure parts of the article, but now it seems nice and I'm waiting for a last review from a strategist so then I'll send it to publishing!

- https://hackmd.io/Yng1EcThTeyLYm2iJR4FAA

**Comment by MarcoWorms** [comment]
Reviewed our docs to fix copy/broken links/add new links/close old PRs

- https://github.com/yearn/yearn-devdocs/pull/260
- https://github.com/yearn/yearn-devdocs/pull/262
- https://github.com/yearn/yearn-devdocs/pull/261

yCRV docs also had some adjustments but nothing major compared to last week

I'm waiting on a review to send last week's article (How to measure risk for DeFi strategies) to publication, I messed up a link in a communication so it was delayed a bit but should be ok by the next one: https://hackmd.io/Yng1EcThTeyLYm2iJR4FAA

I'm starting a new article (no draft yet) to show users/DAOs how to spin up their instance of [yearn-multisig-actions](https://github.com/yearn/yearn-multisig-actions), started by reviewing the repo's docs:

- https://github.com/yearn/yearn-multisig-actions/pull/5

**Comment by MarcoWorms** [comment]
Weekly report!

## Docs

- https://github.com/yearn/yearn-devdocs/pull/265
- https://github.com/yearn/yearn-devdocs/pull/266 (todo: just got FTM and ARBI missing addresses, will add in the same PR)

## yData

- https://github.com/yearn/ydata/pull/106

## veYFI

- mapped out some things to help veYFI responsive UI with https://hackmd.io/xwmd10YCREeDBQbPNLbfZg should be applied by the next report!

## Todos / Followups

- I should help yDaemon docs with copy by next week
- Still want to do an article to show users/DAOs how to spin up their instance of [robowoofy](https://github.com/yearn/yearn-multisig-actions)
- Talk about the opensource weiroll lib

**Comment by MarcoWorms** [comment]
## Docs

- https://github.com/yearn/yearn-devdocs/pull/266
Continued working on the above and merged, now all addresses are in one page: https://docs.yearn.finance/getting-started/products/addresses
- followup: I have queued task to take a deeper look at yDaemon docs, didn't do it yet

## Articles

- Farrah handed over to me the flow to publish the articles so I should send them to Draper directly now, Farrah will still be in the process as a reviewer though!
- The risk article was released https://twitter.com/iearnfinance/status/1585609723008671745
- Followup articles: make a case study for a stETH strategy (to talk about stETH as well in an article), also robowoofy + weiwoll mentioned last week are still queued

## veYFI

- Applied some of the changes proposed to the yearn finance v3 code, now I have to refactor the change I added and finish the others. I'm coordinating this one with Gambito.

**Comment by MarcoWorms** [comment]
## Docs

- Did some overall review on yDaemon docs
  - https://github.com/yearn/ydaemon/pull/113
- Major merged it and I made a tweet to try to show the docs to the world: 
  - https://twitter.com/MarcoWorms/status/1588557518820679680

## Articles

- Started an article on stETH and I learned that we have 2 ways to be exposed to stETH on yearn: through the ETH vault and through the steCRV vault. I started doing things for the article yet but the text should be done by next week. 
  - draft: https://hackmd.io/5L8BMw8WS-WdU2ncFZ4uzA

<details>
<summary>Click to expand Images and diagrams draft:</summary>

![](https://user-images.githubusercontent.com/7863230/200032045-87ffac1a-5870-473a-80b4-9168ffbbb518.png)

![](https://i.imgur.com/enNsZ91.png)

![](https://i.imgur.com/ruBrwNJ.png)

![](https://i.imgur.com/JN7bImy.png)

</details>

**Comment by MarcoWorms** [comment]
## Docs
- https://github.com/yearn/yearn-devdocs/pull/270
- reviewed and merged some other PRs that showed up and fixed typos

## Articles

- stETH article is going but I need more time to finish expanding each section and make more visuals to it, should be done next week! the first part can be read already if anyone wants to see what will it talk about, I'm open to feedbacks!
  - draft: https://hackmd.io/5L8BMw8WS-WdU2ncFZ4uzA
- aligned with Draper to have an article about veYFI ready, made on top of the docs queued for merge, so whenever we release it we can have content to post on socials!

## Vault Reports

- working with toby on making a static page for future public vault reports. We just had a call yesterday to align things, I will focus on styling the page and just now he sent me the data I need to get started!

**Comment by MarcoWorms** [comment]
## Docs

- I'm understanding the dependencies to generate versioned docs from yearn-vaults repo and documenting the process so the next person can generate the docs with less dependency errors
- Fixed preview links for the docs that were using old logo:
![image](https://user-images.githubusercontent.com/7863230/202769937-eb14dd3f-dae8-4d19-a0ce-63c1a0ada831.png)

## Articles
![image](https://user-images.githubusercontent.com/7863230/202769798-cd61b57c-55c7-4c23-b92a-a8e52de319e5.png)
- https://hackmd.io/5L8BMw8WS-WdU2ncFZ4uzA this article draft is done! now sent to about 4 people for technical review and copy improvements, should be done and published by next Friday!

## Vault Reports
- Still working on this one to improve what was done along this week, we had a huge progression but still needs to polish design and some data display to make it 100%. source code is here https://codesandbox.io/s/stoic-vaughan-wz8ul9?file=/src/App.js it picks up .csv and generates a pretty image report, I'm trying to make it so its easy to change themes

preview:

![image](https://user-images.githubusercontent.com/7863230/202769500-ea122e60-aad6-4286-9f65-f42d5e36b820.png)

![image](https://user-images.githubusercontent.com/7863230/202769526-0d48adc9-8986-4c4c-a7b8-d2fa2571c7b7.png)
