### ISSUE TITLE
Fund the DOM.money – an unstoppable bank

### ISSUE THREAD

**Issue by Crypto-arm** [yearn/budget#94]
### Scope

DOM Money is building unstoppable, autonomous non-custodial service financial services for non-crypto users and businesses. We provide an option to drop out of the financial systems of the countries.

Our first product is an unstoppable non-custodial stablecoin wallet with a convenient bank interface built to run forever, ignoring external impacts. Hosted on decentralized permanent hosting with strong encryption and untraceability of all traffic, Wallet includes a portfolio allocation engine that distributes stablecoins across DeFi protocols with weekly autocompounding. It hedges risk across 4+ blockchains and 20+ DeFi products.

**Known problems to solve:**

- Knowledge of crypto technologies:
To get all benefits of crypto products users have to have some knowledge in blockchain technologies.

- Ownership and censorship-resistant storing of capital:
The problem of ownership of money gets more and more critical in modern unstable world. We see how governments and corporations restrict access to bank accounts. Even crypto exchanges start blocking accounts of the average citizen.

- Unattractive interest rates in dollars:
Last but not least the interest rates in dollars remain unattractive. So people are looking for alternative ways of saving their money.

**Benefits to boost the Yearn ecosystem?**

- Attract additional liquidity - we plan to place 30% of all users' funds in Yearn and thus provide additional liquidity to the network.
-  Increase capital efficiency with DOM money ML-driven portfolio allocation engine. 
-  Attract additional funds from crypto newcomers

### Plan

- Our first product is a non-custodial stablecoin wallet with a convenient conventional bank interface.
- DOM is going to be hosted on decentralized permanent hosting and with strong encryption and untraceability of all traffic. - Wallet includes a portfolio allocation engine that distributes stablecoins across DeFi protocols with weekly autocompounding. It hedges risk across 4+ blockchains and 20+ DeFi products.
- We plan to place 30% of all users' funds in Yearn network and thus provide additional liquidity to the network.

### Deadline

2022-12-25

### People

Team of 7 people and growing

Nikolai Grigoriev, co-founder & CEO
Stepan Mytchyk, co-founder & Head of Crypro
Andrii, co-founder & CTO
Denis, UX
Artem, Chief Investment Officer
Ihor, Front end developer
Albert, Business Development

### Money

Budget plan:

80% - Team expansion, hiring, salaries
2 solidity developers ML-engineer
Community manager
Marketing lead
10% Paid services, subscriptions additional costs 
10% Paid marketing at platforms like https://beta.layer3.xyz/

Amount: 
$50K - integration of Yearn in Ethereum, Arbitrum, Fantom.
$120K - development of stablecoin focused cross-chain ML-driven portfolio allocation engine based on Yearn liquidity pools with evolutionary models and cross-chain assets transfers.

### Amount

$50K - integration of Yearn in Ethereum, Arbitrum, Fantom; $120K - development of stablecoin focused cross-chain ML-driven portfolio allocation engine based on Yearn liquidity pools with evolutionary models and cross-chain assets transfers.

### Wallet address

0x0

### Reporting

- [X] I agree to post weekly updates

**Comment by milkyklim** [comment]
Thanks for request. Unfortunately, the grant has been rejected as it falls outside of yearn’s direct scope.
