### ISSUE TITLE
Continue maintaining blog.yearn.finance + French content

### ISSUE THREAD

**Issue by qosmonot** [yearn/budget#99]
### Scope

This is a request to merge and extend https://github.com/yearn/budget/issues/66 & https://github.com/yearn/budget/issues/75.

### Plan

The plan, as in the previous requests, is to maintain the blog.yearn.finance product, to keep adding content and translations (currently FR actively). 

We believe that this work is necessary, and especially during a bear market, as education and communication is key and should not be forgotten.

It is essential to control our channel of comms, and improving SEO vs. only using medium etc. We should also keep maintaining and sharing content fron our blog, so users get use to read it and use it as the main place for informations about Yearn. It also leverages the work done by other teams (Docs, brand/comms).

I ask for a monthly grant for the following ~3 months ending on December 31st. 2000 DAI per month.

For other scope and plan, please refer to https://github.com/yearn/budget/issues/66 & https://github.com/yearn/budget/issues/75.

Please not that budget is reduced compared to our previous budget request (2000 + 1000 /month).
*Note: If yBudget agrees to keep and renew the previous budget, we won't complain :)

### Deadline

2022-12-31

### People

Cryptouf: content watch, FR translations, FR community outreach
qosmonot: organization, coordination, review
Major: helping out on the organization side *(not receiving remuneration from this grant)*

### Money

2,000 DAI p/m, split between the contributors of blog.yearn.finance (currently Cryptouf, qosmonot)
Stream with an evaluation after three months (December EOM).

### Amount

2,000 DAI p/m

### Wallet address

~~0x4bBa34aE170fB02F8502e237969B054c5F1D14AF~~
0x3D935C7bf3Ec8891C17b074b841d940264f073c5

### Reporting

- [X] I agree to post weekly updates

**Comment by 0x7171** [comment]
This is approved, stream to be set up

**Comment by banteg** [comment]
please provide a wallet address so we can start the stream, thank you

**Comment by qosmonot** [comment]
OK done. updated with a wallet address. Thank you

**Comment by cryptoouf-blog** [comment]
Since the stream didn't start yet. Would be amazing if we could end it 3months after the beginning of it, and not the December 31st (as it will be only 2 months) , as mentioned in the proposal.

**Comment by banteg** [comment]
you can find the claiming ui here https://llamapay.io/vesting

**Comment by qosmonot** [comment]
edited with a new address
